### ISSUE TITLE
Cmake error when building

### ISSUE THREAD

**Issue by username227** [ptyfyre/mandarine-neo#108]
### Issue

Hi, I am the maintainer of the package on the AUR for arch. Recently, i'm running into an error while packaging the program using the cmake --install command. I am running into the following error:

`==> Starting package()...
-- Install configuration: "None"
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/lib/libenet.a
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/callbacks.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/enet.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/protocol.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/types.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/time.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/list.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/utility.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/unix.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/include/enet/win32.h
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/bin/mandarine
-- Installing: /build/mandarine-git/pkg/mandarine-git/usr/bin/mandarine-room
CMake Error at build/cmake_install.cmake:69 (file):
  file INSTALL cannot find
  "/build/mandarine-git/src/mandarine/dist/mandarine-qt.desktop": No such
  file or directory.`

This appears to be a problem that has crept into the cmake files.

**Comment by Gamer64ytb** [comment]
Recently, SDL interface got removed and now its just "mandarine.desktop", may be that?

**Comment by username227** [comment]
yes, that would make sense. if the file name changed but the cmake instructions didn't, then it could be why we have an error.

**Comment by username227** [comment]
any idea how to fix? I've tried a dirty patch on the cmake_install.cmake file, but i can't get it working. I'm guessing it's an easy fix for you. thanks!

**Comment by rtiangha** [comment]
@username227 Change line 456 in the root `CMakeLists.txt` from this:

```
    install(FILES "${PROJECT_SOURCE_DIR}/dist/mandarine-qt.desktop"
```

to this:

```
    install(FILES "${PROJECT_SOURCE_DIR}/dist/mandarine.desktop"
```

**Comment by username227** [comment]
> @username227 Change line 456 in the root `CMakeLists.txt` from this:
> 
> ```
>     install(FILES "${PROJECT_SOURCE_DIR}/dist/mandarine-qt.desktop"
> ```
> 
> to this:
> 
> ```
>     install(FILES "${PROJECT_SOURCE_DIR}/dist/mandarine.desktop"
> ```



> @username227 Change line 456 in the root `CMakeLists.txt` from this:
> 
> ```
>     install(FILES "${PROJECT_SOURCE_DIR}/dist/mandarine-qt.desktop"
> ```
> 
> to this:
> 
> ```
>     install(FILES "${PROJECT_SOURCE_DIR}/dist/mandarine.desktop"
> ```

Yup, that works, so you should be good for a commit. thanks so much!

**Comment by username227** [comment]
Completed with commit 10233
