### ISSUE TITLE
Long Loading time (10-15 seconds)

### ISSUE THREAD

**Issue by newuser9290** [ptyfyre/mandarine-neo#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mandarine 1.1

### Description of Issue

I've redumped everything to make it as clean of an install as possible, but any game will stay on the loading screen for upwards of 10-15 seconds. I have this same issue on Lime3DS Pablo's Citra as well as Mandarine latest. Only Citra MMJ doesn't cause long loading times. 

### Expected Behavior

Should load instantly maybe 2-3 seconds if large game

### Reproduction Steps

Load game

### Log File

[mandarine_log.txt](https://github.com/user-attachments/files/17007597/mandarine_log.txt)

### System Configuration

CPU: SnapDragon 8Gen 3
GPU/Driver: Adreno 750 (Turnip Driver 24.3.0 R6)
RAM:12
OS:Android14

**Comment by Shadowdark44** [comment]
It may be the home menu, if you have it installed.

**Comment by newuser9290** [comment]
> It may be the home menu, if you have it installed.

I've tried both with and without HOME installed. The game speed etc is perfectly fine, its just the forever loading thats the issue for me

**Comment by newuser9290** [comment]
Closed due to me being a dummy. Was away from android too long and forgot how the file structure works with new permissions. All is well.
