### ISSUE TITLE
Support Play Store/F-Droid

### ISSUE THREAD

**Issue by dnet890** [ptyfyre/mandarine-neo#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I think it will be best if this app will be available on Play store or F Droid for greater discoverability 

### Why would this feature be useful?

I think it will be better if this app available for Plsy store or F droid for automatic updates

**Comment by ghost** [comment]
You can use [Obtainium](https://github.com/ImranR98/Obtainium) for auto-updates on Android, for now we don't plan to be on either platform
