### ISSUE TITLE
Pretendo work

### ISSUE THREAD

**Issue by mcoldani** [ptyfyre/mandarine-neo#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Im suggesting to implement pretendo, or make it works, like citra fork of Pablomk7, this citra is amazing im sooo happy, cuz it works perfect (snapdragon 662, Motorola G8), and make work some virtual console games (zelda minish cap i wanna play it here so i dont use another emulator and VC adds some things so make it easy to play)

### Why would this feature be useful?

It will make ur project more recognize and make other developers know ur protect cuz of community.

**Comment by TwistedTempest** [comment]
This project is forked from and shares all of the same code as PabloMK7's Citra (excluding the enhancements), it can connect all the same if you set it up

**Comment by mcoldani** [comment]
Hi, then idk whats my problem lol, like idk what i am doing wrong, i use the same files but just doesn't connect to pretendo

**Comment by mcoldani** [comment]
Here's my log, idk what im doing wrong.. it keeps on connection forever (on confi whenever i test a connection) and on the friend list it just never connects, on games it just keeps on loading whenever I try to Connect online
[citra_log.txt.old.txt](https://github.com/Gamer64ytb/Citra-Enhanced/files/15360530/citra_log.txt.old.txt)

**Comment by Radu13** [comment]
Be aware pablo's citra fork latest versions DO NOT work and do not connect to pretendo succesfully, latest pablo version that works and I'm aware of is 11c4b65 (found with waybackmachine) but it should match citra 2.1 version!
I don't think Pablo has fixed the newer versions yet, so I suggest open an issue on his repository about this.

**Comment by SuperPat45** [comment]
It would be a lot easier for customer to have an option in the web tab to enable online features with Pretendo, like cemu does.
And auto-patch everything on the fly, so it will no more need to manually install patches.
