### ISSUE TITLE
Android APK not working 

### ISSUE THREAD

**Issue by Angel59x** [ptyfyre/mandarine-neo#4]
### Issue

When I try to open APK for Android does not work I get it error message

**Comment by CorruptionVR** [comment]
what error message? after what happens? @Angel59x

**Comment by Angel59x** [comment]
When I tried to install, it just gives me error when I get home later. I’ll take a picture.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CorruptionVR** [comment]
what exactly does it say? "Failed to parse package", "App not installed as package conflicts with an existing package", something else?
@Angel59x

**Comment by Angel59x** [comment]
I don’t recall when I get home. I’ll check my  Odin 2

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Angel59x** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Angel59x** [comment]
There were a problem parsing the package

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CorruptionVR** [comment]
try redownloading the apk. it worked fine for me

**Comment by Angel59x** [comment]
Does it conflict with last Canary build of Citra

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CorruptionVR** [comment]
if it did, it would give you this error "App not installed as package conflicts with an existing package"

**Comment by Angel59x** [comment]
I found out what it was it conflict with last Canary built of Citra

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Gamer64ytb** [comment]
Anyways, I changed package for the next version
