### ISSUE TITLE
after loading shaders the emulator closes in open gl graphics api

### ISSUE THREAD

**Issue by gustavoariel61** [ptyfyre/mandarine-neo#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build

last dev

### Description of Issue

In the latest version 1.2.0, when you run any game, it loads the shaders and at the end the emulator closes. This only happens when the graphics api is open gl. When I switch to Vulkan, the games run but the games have never worked well for me. Vulkan with the previous version does work correctly with the 2 graphics APIs, which is why I have concluded that it is a bug.

[https://www.youtube.com/watch?v=-ycPNHWkgag](url)

### Expected Behavior

In the previous version it worked perfectly, in this one it should work the same

### Reproduction Steps

just by having the opengl api activated
![Sin título](https://github.com/CitraEnhanced/citra/assets/167393101/818ecb25-f3e9-4701-901e-36f8414f84f9)

### Log File

[citra_log.txt.txt](https://github.com/CitraEnhanced/citra/files/15442459/citra_log.txt.txt)

### System Configuration

CPU: Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
GPU/Driver: Intel(R) HD Graphics 520
RAM: 11.89 GiB
OS: Windows 10 Version 22H2 (Build 19045.2006)

**Comment by Gamer64ytb** [comment]
Hello, can you try this build? Trying to fix your issue

https://github.com/CitraEnhanced/citra/actions/runs/9235020987

Builds will be available on 10 minutes

**Comment by gustavoariel61** [comment]
Thank you very much for the response, how can I download the compilation to test?

**Comment by ghost** [comment]
> Thank you very much for the response, how can I download the compilation to test?

Scroll down on our readme and downlaod the dev builds

**Comment by gustavoariel61** [comment]
good friends, with the dev update citra-windows-msvc-20240527-f2f0762 the closing of the emulator with opengl was solved and it works a little more smoothly but there are some games that jerk like mario kar 7 good job friends if you need a tester to test the dev versions here I can help you thank you very much and excellent work

**Comment by ghost** [comment]
We'll appreciate any help, contact us on Discord so we can talk easier
