### ISSUE TITLE
Bravely Default crash 

### ISSUE THREAD

**Issue by Canyrex12** [ptyfyre/mandarine-neo#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build

Last builds 

### Description of Issue

When you load the game and move the character, it crashes and returns to the menu.

### Expected Behavior

That the game does not crash 

### Reproduction Steps

1-Open Citra Enhanced.
2-Play "Bravely Default".
3-Move the player.

### Log File

[citra_log.txt.old.txt](https://github.com/CitraEnhanced/citra/files/15448842/citra_log.txt.old.txt)

### System Configuration

CPU: Unisoc T606
GPU/Driver:Mali G57 
RAM:3 GB 
OS:

**Comment by Canyrex12** [comment]
And this is the problem 

https://github.com/CitraEnhanced/citra/assets/163220722/dd1969ae-c94e-47bd-b073-320a764d8204

**Comment by rtiangha** [comment]
They would probably need more information.

* Vulkan or OpenGL?
* Did it ever work on Citra Enhanced? If so, what build(s)?
* Does it work on Lime3DS or PabloMK7's fork? Or does it not either?

Also, I think that's the wrong log file; there's nothing about Bravely Default in it.

**Comment by Canyrex12** [comment]
-Vulkan

 -I only know that it stopped working from #431 0f41dd5 (after this it doesn't work) and it worked again (with some crashes) in the last compilation. 

-I have not tested it in the PabloMk7 fork, and in Lime3ds it works correctly so far.

**Comment by Canyrex12** [comment]
Update: The problem is in several games while relaxed precision decorations are active.
