### ISSUE TITLE
Compile shaders before starting

### ISSUE THREAD

**Issue by TwistedTempest** [ptyfyre/mandarine-neo#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

This is just a bump of fordel-0's suggestion from PabloMK7's Citra distro upon which this is based. Essentially, if this were possible to implement in a similar way to the feature in Dolphin or Cemu it would be nice to be able to compile shaders at runtime instead of just-in-time.

### Why would this feature be useful?

Games such as the gen 6 Pokémon games that compile their shaders as they become needed have long breaks when transitioning between 3D environments and would benefit greatly from the ability to compile and preload these shaders ahead of time.

**Comment by Ishan09811** [comment]
@TwistedTempest 
if you mean to compile shaders before starting a game then citra already do this

**Comment by TwistedTempest** [comment]
> @TwistedTempest if you mean to compile shaders before starting a game then citra already do this

It can compile already cached shaders but still needs to compile them in real time if they haven't been used before (i.e. using Eon Flute). The stutter is absolved by using async shader compilation but then there is the issue of visual glitching

**Comment by TwistedTempest** [comment]
Closing as the method used to achieve this functionality in Dolphin, Ubershaders, is fundamentally different from what I have described and according to their documentation compiling shaders before starting is not possible.
