### ISSUE TITLE
Add FMV Hack

### ISSUE THREAD

**Issue by i0x404** [ptyfyre/mandarine-neo#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

FMV Hack from Citra MMJ

### Why would this feature be useful?

There are several games that would run better by implementing this, for example I tried Inazuma Eleven Go and Adventure Time : Finn & Jake Investigations on Citra MMJ and it worked perfectly with the FMV Hack but as soon as I disable the fps would drop instantly.
(in Citra Enhanced same issue FPS is at 5-8)

**Comment by Gamer64ytb** [comment]
Raise CPU Ticks does almost the same thing as FMV Hack. Try

**Comment by i0x404** [comment]
Tried it with Finn and Jake Investigations and it worked thanks a lot.
