### ISSUE TITLE
Blue screen issue using Vulkan and OpenGL with frameskip x2 option

### ISSUE THREAD

**Issue by LuisPerss** [ptyfyre/mandarine-neo#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build

Ultima actualizacion,1.3

### Description of Issue

The problem is caused by using the frameskip option in the debugging section, it says that there may be errors depending on the API (Vulkan or OpenGL) but in both it is the same case, in both you see the blue screen, very rarely fixes it and when it looks good without that annoying blue screen, the game continues playing (that is, the sound) but it stays stuck, and be careful, this frame skip option is good for increasing performance since in the little that is You can appreciate the game, it was going from 48 to 60 fps, not stable but high, in only 2x or 4x frameskip, please fix that error in the future, that could solve at least a little more performance.

### Expected Behavior

This frame skip option is good to increase performance since in the little that you can see the game, it went from 48 to 60 fps, not stable but high, in only 2x or 4x frameskip, please fix that error in the future That could solve at least a little more performance.

As said before, it has the problem of not reproducing the image and then it freezes with sound, but the fps increases, it would be good if that was fixed to be able to use this option in a good way, thus gaining performance.

### Reproduction Steps

The error occurs when the frameskip option is enabled in debug.

### Log File

![Screenshot_20240628_225727_Citra Enhanced](https://github.com/CitraEnhanced/citra/assets/154714667/4dd01133-b5c0-40bf-8408-4808d4d345cc)

### System Configuration

CPU:Exynos 850
GPU/Driver:
RAM:4GB
OS:Android 13

**Comment by LuisPerss** [comment]
I tried this option (frameskip) with Mario 3D Land and New Super Mario Bros 2.

**Comment by Gamer64ytb** [comment]
Actually this bug got fixed, if you want to try it now, you can try it from https://github.com/mandarine3ds/mandarine/actions/runs/10126025053
