### ISSUE TITLE
The icon zoom is ugly

### ISSUE THREAD

**Issue by dreamboyn81** [ptyfyre/mandarine-neo#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

1. I hope it is possible to add option to switch back to list display.
2. or add option to adjust icon display size.
3. or long press the game to change the cover (similar to PizzaBoy and AetherSX2).
![Screenshot_2024-06-29-16-30-59-821_org gamerytb citra canary](https://github.com/CitraEnhanced/citra/assets/15012771/20e20bb6-5fd4-472a-83be-c01ebd3f0ecc)

### Why would this feature be useful?

Make the emulator interface look better

**Comment by JamesAk475styles345** [comment]
Yes the game icon looks blurry

**Comment by Gamer64ytb** [comment]
Next version will get stock cover designs

**Comment by JamesAk475styles345** [comment]
Ok
