### ISSUE TITLE
run from Daijisho?

### ISSUE THREAD

**Issue by ren7o** [ptyfyre/mandarine-neo#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hey! I searched almost everywhere but could not find any info about this. Is there any chance to run games directly via Daijisho?

### Why would this feature be useful?

It helps ton of retro handehlds users.

**Comment by vhoxha08** [comment]
Daijisho has already added mandarine3ds as a player. Issue needs to be closed.
