### ISSUE TITLE
Really questionable commits in non-master branches

### ISSUE THREAD

**Issue by ghost** [ptyfyre/mandarine-neo#76]
### Issue

The commit history on non-maser branches like the legacy branch is shady to say the least but these stuck out to me

https://github.com/CitraEnhanced/citra/commit/3b785aacf8d4cac5f9225e0b8b10e3ec6d7043de

https://github.com/CitraEnhanced/citra/commit/15d242539ab87f788605467e5ce5597377ac6a24

You might wanna do something king

**Comment by Gamer64ytb** [comment]
These files were made by Enhanced project, meaning that gives full access for putting our own GPL header.

**Comment by ghost** [comment]
My bad, these are your files but for some reason, you copy-pasted old headers and pushed it

Lol
