### ISSUE TITLE
Emulator instantly crashing when using Vulkan on hardware with Vulkan 1.2

### ISSUE THREAD

**Issue by Colmines92** [ptyfyre/mandarine-neo#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All of them

### Description of Issue

When I select Vulkan as the graphics engine and try to run a game, the emulator instantly crashes. I know I have old hardware, although there was a time at the beginning when the team responsible for Citra was making the first Vulkan implementations where it didn’t crash for me. There were graphical errors in most titles, but back then, since it was experimental, even on modern hardware it caused some graphical errors. When they made it ‘stable,’ it never worked for me again on my GTX 650, but not just for me. I have a friend with 6th generation Intel integrated graphics who also didn’t experience crashes in the early implementations and then did. This is a bug in the original Citra.

### Expected Behavior

Either start the game, even with graphical errors.
Or detect on game launch if it'll crash the emu and handle the exception to display a proper message and prevent the emulator from crashing.

### Reproduction Steps

Set Vulkan as 3d renderer.
Launch any game.
(Only on hardware without Vulkan 1.3 support I suppose)

### Log File

[mandarine_log.txt](https://github.com/user-attachments/files/16637661/mandarine_log.txt)

### System Configuration

CPU: Intel core-i7 4790
GPU/Driver: Nvidia Geforce GTX 650
RAM: 16gb @1600 Mhz
OS: Microsoft Windows 10 22h2

**Comment by Zil0s** [comment]
I have the same problem as you I tried a lot of old versions of citra just to make sure and other 3ds emulators and i get the same crash when i try to open a game selecting vulkan api, Someone mentioned that choosing the graphics card manually under api option after choosing fixs it, It didn't work for me, Give it a try and tell me if it worked

System specs
CPU:intel core i5 4590
GPU: gt 730 2g gddr5
Driver:475.14
Ram: 8 gb

OS: Windows 10 22h2

Edit: log


[mandarine_log.txt.old.txt](https://github.com/user-attachments/files/16742000/mandarine_log.txt.old.txt)

**Comment by i0x404** [comment]
fixed with [this](https://github.com/mandarine3ds/mandarine/actions/runs/10509656153)


test it out and see

**Comment by Zil0s** [comment]
Yeah it worked
 Thank you

**Comment by Colmines92** [comment]
Yes!
I can confirm it works now.
Thank you very much!
