### ISSUE TITLE
Implement 0.5 or 0.75 resolution scale like yuzu 

### ISSUE THREAD

**Issue by daeklo4** [ptyfyre/mandarine-neo#91]
### Issue

Please implement this resolution scale for more fps on low end devices like yuzu

**Comment by TwistedTempest** [comment]
Not to be a snob, but running 3DS games at half resolution would be literally unplayable to most. At the point where running the games at native resolution is unmanageable, it's more likely that your device is unable to handle the overhead of emulation than struggling to render 240p graphics.

**Comment by ghost** [comment]
0.50 would be less than 144p 💀 

These guys are out of earth
